name: {{app_name}}
description: A new Khadem Dart project.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  khadem:
    path: D:\Users\Khedr\src\khadem

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.6
