// Mocks generated by Mockito 5.4.6 from annotations
// in khadem/test/core/exception/exception_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i2;

import 'package:khadem/khadem.dart' as _i8;
import 'package:khadem/src/core/http/cookie.dart' as _i7;
import 'package:khadem/src/core/http/request/request.dart' as _i9;
import 'package:khadem/src/core/http/response/response_body.dart' as _i5;
import 'package:khadem/src/core/http/response/response_headers.dart' as _i3;
import 'package:khadem/src/core/http/response/response_renderer.dart' as _i6;
import 'package:khadem/src/core/http/response/response_status.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpRequest_0 extends _i1.SmartFake implements _i2.HttpRequest {
  _FakeHttpRequest_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseHeaders_1 extends _i1.SmartFake
    implements _i3.ResponseHeaders {
  _FakeResponseHeaders_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseStatus_2 extends _i1.SmartFake
    implements _i4.ResponseStatus {
  _FakeResponseStatus_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseBody_3 extends _i1.SmartFake implements _i5.ResponseBody {
  _FakeResponseBody_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseRenderer_4 extends _i1.SmartFake
    implements _i6.ResponseRenderer {
  _FakeResponseRenderer_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCookies_5 extends _i1.SmartFake implements _i7.Cookies {
  _FakeCookies_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_6 extends _i1.SmartFake implements _i8.Response {
  _FakeResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Response].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponse extends _i1.Mock implements _i8.Response {
  MockResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HttpRequest get raw => (super.noSuchMethod(
        Invocation.getter(#raw),
        returnValue: _FakeHttpRequest_0(
          this,
          Invocation.getter(#raw),
        ),
      ) as _i2.HttpRequest);

  @override
  bool get sent => (super.noSuchMethod(
        Invocation.getter(#sent),
        returnValue: false,
      ) as bool);

  @override
  _i3.ResponseHeaders get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: _FakeResponseHeaders_1(
          this,
          Invocation.getter(#headers),
        ),
      ) as _i3.ResponseHeaders);

  @override
  _i4.ResponseStatus get statusManager => (super.noSuchMethod(
        Invocation.getter(#statusManager),
        returnValue: _FakeResponseStatus_2(
          this,
          Invocation.getter(#statusManager),
        ),
      ) as _i4.ResponseStatus);

  @override
  int get statusCode => (super.noSuchMethod(
        Invocation.getter(#statusCode),
        returnValue: 0,
      ) as int);

  @override
  _i5.ResponseBody get body => (super.noSuchMethod(
        Invocation.getter(#body),
        returnValue: _FakeResponseBody_3(
          this,
          Invocation.getter(#body),
        ),
      ) as _i5.ResponseBody);

  @override
  _i6.ResponseRenderer get renderer => (super.noSuchMethod(
        Invocation.getter(#renderer),
        returnValue: _FakeResponseRenderer_4(
          this,
          Invocation.getter(#renderer),
        ),
      ) as _i6.ResponseRenderer);

  @override
  _i7.Cookies get cookieHandler => (super.noSuchMethod(
        Invocation.getter(#cookieHandler),
        returnValue: _FakeCookies_5(
          this,
          Invocation.getter(#cookieHandler),
        ),
      ) as _i7.Cookies);

  @override
  void setRequest(_i9.Request? request) => super.noSuchMethod(
        Invocation.method(
          #setRequest,
          [request],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Response status(int? code) => (super.noSuchMethod(
        Invocation.method(
          #status,
          [code],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #status,
            [code],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response setStatusCode(int? code) => (super.noSuchMethod(
        Invocation.method(
          #setStatusCode,
          [code],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #setStatusCode,
            [code],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response header(
    String? name,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #header,
          [
            name,
            value,
          ],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #header,
            [
              name,
              value,
            ],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response withHeaders(Map<String, String>? headers) => (super.noSuchMethod(
        Invocation.method(
          #withHeaders,
          [headers],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #withHeaders,
            [headers],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response cookie(
    String? name,
    String? value, {
    String? domain,
    String? path = '/',
    DateTime? expires,
    Duration? maxAge,
    bool? httpOnly = false,
    bool? secure = false,
    String? sameSite,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cookie,
          [
            name,
            value,
          ],
          {
            #domain: domain,
            #path: path,
            #expires: expires,
            #maxAge: maxAge,
            #httpOnly: httpOnly,
            #secure: secure,
            #sameSite: sameSite,
          },
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #cookie,
            [
              name,
              value,
            ],
            {
              #domain: domain,
              #path: path,
              #expires: expires,
              #maxAge: maxAge,
              #httpOnly: httpOnly,
              #secure: secure,
              #sameSite: sameSite,
            },
          ),
        ),
      ) as _i8.Response);

  @override
  void send(String? text) => super.noSuchMethod(
        Invocation.method(
          #send,
          [text],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendJson(dynamic data) => super.noSuchMethod(
        Invocation.method(
          #sendJson,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void json(dynamic data) => super.noSuchMethod(
        Invocation.method(
          #json,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendHtml(String? html) => super.noSuchMethod(
        Invocation.method(
          #sendHtml,
          [html],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void html(String? html) => super.noSuchMethod(
        Invocation.method(
          #html,
          [html],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> file(
    _i2.File? file, {
    String? contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #file,
          [file],
          {#contentType: contentType},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> back({String? fallback = '/'}) => (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {#fallback: fallback},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void problem({
    required String? title,
    required int? status,
    String? detail,
    String? type,
    String? instance,
    Map<String, dynamic>? extensions,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #problem,
          [],
          {
            #title: title,
            #status: status,
            #detail: detail,
            #type: type,
            #instance: instance,
            #extensions: extensions,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> format(Map<String, Function>? formats) =>
      (super.noSuchMethod(
        Invocation.method(
          #format,
          [formats],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> download(
    _i2.File? file, {
    String? name,
    bool? inline = false,
    String? contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [file],
          {
            #name: name,
            #inline: inline,
            #contentType: contentType,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> redirect(
    String? url, {
    int? status = 302,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #redirect,
          [url],
          {#status: status},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> stream<T>(
    _i10.Stream<T>? stream, {
    String? contentType = 'application/octet-stream',
    Map<String, String>? headers,
    List<int> Function(T)? toBytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stream,
          [stream],
          {
            #contentType: contentType,
            #headers: headers,
            #toBytes: toBytes,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> view(
    String? viewName, {
    Map<String, dynamic>? data = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #view,
          [viewName],
          {#data: data},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void bytes(
    List<int>? bytes, {
    String? contentType = 'application/octet-stream',
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #bytes,
          [bytes],
          {#contentType: contentType},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void jsonPretty(
    dynamic data, {
    int? indent = 2,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #jsonPretty,
          [data],
          {#indent: indent},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void empty() => super.noSuchMethod(
        Invocation.method(
          #empty,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Response ok() => (super.noSuchMethod(
        Invocation.method(
          #ok,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #ok,
            [],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response created() => (super.noSuchMethod(
        Invocation.method(
          #created,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #created,
            [],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response accepted() => (super.noSuchMethod(
        Invocation.method(
          #accepted,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #accepted,
            [],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response noContent() => (super.noSuchMethod(
        Invocation.method(
          #noContent,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #noContent,
            [],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response badRequest() => (super.noSuchMethod(
        Invocation.method(
          #badRequest,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #badRequest,
            [],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response unauthorized() => (super.noSuchMethod(
        Invocation.method(
          #unauthorized,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #unauthorized,
            [],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response forbidden() => (super.noSuchMethod(
        Invocation.method(
          #forbidden,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #forbidden,
            [],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response notFound() => (super.noSuchMethod(
        Invocation.method(
          #notFound,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #notFound,
            [],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response internalServerError() => (super.noSuchMethod(
        Invocation.method(
          #internalServerError,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #internalServerError,
            [],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response cors({
    String? allowOrigin,
    String? allowMethods,
    String? allowHeaders,
    String? exposeHeaders,
    bool? allowCredentials = false,
    int? maxAge,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cors,
          [],
          {
            #allowOrigin: allowOrigin,
            #allowMethods: allowMethods,
            #allowHeaders: allowHeaders,
            #exposeHeaders: exposeHeaders,
            #allowCredentials: allowCredentials,
            #maxAge: maxAge,
          },
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #cors,
            [],
            {
              #allowOrigin: allowOrigin,
              #allowMethods: allowMethods,
              #allowHeaders: allowHeaders,
              #exposeHeaders: exposeHeaders,
              #allowCredentials: allowCredentials,
              #maxAge: maxAge,
            },
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response security({
    bool? enableHsts = false,
    bool? enableCsp = false,
    bool? enableXFrameOptions = true,
    bool? enableXContentTypeOptions = true,
    String? cspPolicy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #security,
          [],
          {
            #enableHsts: enableHsts,
            #enableCsp: enableCsp,
            #enableXFrameOptions: enableXFrameOptions,
            #enableXContentTypeOptions: enableXContentTypeOptions,
            #cspPolicy: cspPolicy,
          },
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #security,
            [],
            {
              #enableHsts: enableHsts,
              #enableCsp: enableCsp,
              #enableXFrameOptions: enableXFrameOptions,
              #enableXContentTypeOptions: enableXContentTypeOptions,
              #cspPolicy: cspPolicy,
            },
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response cache(String? value) => (super.noSuchMethod(
        Invocation.method(
          #cache,
          [value],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #cache,
            [value],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response noCache() => (super.noSuchMethod(
        Invocation.method(
          #noCache,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #noCache,
            [],
          ),
        ),
      ) as _i8.Response);

  @override
  _i8.Response gzip() => (super.noSuchMethod(
        Invocation.method(
          #gzip,
          [],
        ),
        returnValue: _FakeResponse_6(
          this,
          Invocation.method(
            #gzip,
            [],
          ),
        ),
      ) as _i8.Response);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i8.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.LogLevel get minimumLevel => (super.noSuchMethod(
        Invocation.getter(#minimumLevel),
        returnValue: _i8.LogLevel.debug,
      ) as _i8.LogLevel);

  @override
  String get defaultChannel => (super.noSuchMethod(
        Invocation.getter(#defaultChannel),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#defaultChannel),
        ),
      ) as String);

  @override
  set minimumLevel(_i8.LogLevel? level) => super.noSuchMethod(
        Invocation.setter(
          #minimumLevel,
          level,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadFromConfig(
    _i8.ConfigInterface? config, {
    String? channel = 'app',
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #loadFromConfig,
          [config],
          {#channel: channel},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addHandler(
    _i8.LogHandler? handler, {
    String? channel = 'app',
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addHandler,
          [handler],
          {#channel: channel},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDefaultChannel(String? channel) => super.noSuchMethod(
        Invocation.method(
          #setDefaultChannel,
          [channel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debug(
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #debug,
          [message],
          {
            #context: context,
            #stackTrace: stackTrace,
            #channel: channel,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {
            #context: context,
            #stackTrace: stackTrace,
            #channel: channel,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warning(
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #warning,
          [message],
          {
            #context: context,
            #stackTrace: stackTrace,
            #channel: channel,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #context: context,
            #stackTrace: stackTrace,
            #channel: channel,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void critical(
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #critical,
          [message],
          {
            #context: context,
            #stackTrace: stackTrace,
            #channel: channel,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    _i8.LogLevel? level,
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            level,
            message,
          ],
          {
            #context: context,
            #stackTrace: stackTrace,
            #channel: channel,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
