// Mocks generated by Mockito 5.4.6 from annotations
// in khadem/test/core/exception/exception_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:khadem/contracts.dart' as _i3;
import 'package:khadem/src/core/logging/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i2.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.LogLevel get minimumLevel =>
      (super.noSuchMethod(
            Invocation.getter(#minimumLevel),
            returnValue: _i3.LogLevel.debug,
          )
          as _i3.LogLevel);

  @override
  String get defaultChannel =>
      (super.noSuchMethod(
            Invocation.getter(#defaultChannel),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#defaultChannel),
            ),
          )
          as String);

  @override
  set minimumLevel(_i3.LogLevel? level) => super.noSuchMethod(
    Invocation.setter(#minimumLevel, level),
    returnValueForMissingStub: null,
  );

  @override
  void loadFromConfig(_i3.ConfigInterface? config, {String? channel = 'app'}) =>
      super.noSuchMethod(
        Invocation.method(#loadFromConfig, [config], {#channel: channel}),
        returnValueForMissingStub: null,
      );

  @override
  void addHandler(_i3.LogHandler? handler, {String? channel = 'app'}) =>
      super.noSuchMethod(
        Invocation.method(#addHandler, [handler], {#channel: channel}),
        returnValueForMissingStub: null,
      );

  @override
  void setDefaultChannel(String? channel) => super.noSuchMethod(
    Invocation.method(#setDefaultChannel, [channel]),
    returnValueForMissingStub: null,
  );

  @override
  void debug(
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) => super.noSuchMethod(
    Invocation.method(
      #debug,
      [message],
      {#context: context, #stackTrace: stackTrace, #channel: channel},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void info(
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) => super.noSuchMethod(
    Invocation.method(
      #info,
      [message],
      {#context: context, #stackTrace: stackTrace, #channel: channel},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void warning(
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) => super.noSuchMethod(
    Invocation.method(
      #warning,
      [message],
      {#context: context, #stackTrace: stackTrace, #channel: channel},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void error(
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#context: context, #stackTrace: stackTrace, #channel: channel},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void critical(
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) => super.noSuchMethod(
    Invocation.method(
      #critical,
      [message],
      {#context: context, #stackTrace: stackTrace, #channel: channel},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void log(
    _i3.LogLevel? level,
    String? message, {
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
    String? channel,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [level, message],
      {#context: context, #stackTrace: stackTrace, #channel: channel},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
