import '../../core/database/schema/blueprint.dart';

/// Interface for building or modifying database schemas.
///
/// This builder is used in migrations to define table structure.
abstract interface class SchemaBuilder {
  /// Creates a new table with the given [tableName] and [callback].
  ///
  /// The [callback] receives a [Blueprint] to define the table columns and constraints.
  void create(String tableName, void Function(Blueprint table) callback);

  /// Creates the table if it does not exist already.
  void createIfNotExists(
      String tableName, void Function(Blueprint table) callback);

  /// Drops the specified table.
  void drop(String tableName);

  /// Drops the table only if it exists.
  void dropIfExists(String tableName);

  /// Returns the raw list of SQL queries generated by the builder.
  List<String> get queries;
}
