// Mocks generated by Mockito 5.4.6 from annotations
// in khadem/test/auth/jwt_driver_exception_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:khadem/src/modules/auth/contracts/auth_config.dart' as _i2;
import 'package:khadem/src/modules/auth/contracts/token_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthConfig extends _i1.Mock implements _i2.AuthConfig {
  MockAuthConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> getProvider(String? providerKey) => (super.noSuchMethod(
        Invocation.method(
          #getProvider,
          [providerKey],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  List<Map<String, dynamic>> getProvidersForGuard(String? guardName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProvidersForGuard,
          [guardName],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<String> getAllProviderKeys() => (super.noSuchMethod(
        Invocation.method(
          #getAllProviderKeys,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Map<String, dynamic> getGuard(String? guardName) => (super.noSuchMethod(
        Invocation.method(
          #getGuard,
          [guardName],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String getDefaultGuard() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultGuard,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getDefaultGuard,
            [],
          ),
        ),
      ) as String);

  @override
  String getDefaultProvider() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultProvider,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getDefaultProvider,
            [],
          ),
        ),
      ) as String);

  @override
  T getOrDefault<T>(
    String? key,
    T? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrDefault,
          [
            key,
            defaultValue,
          ],
        ),
        returnValue: _i3.dummyValue<T>(
          this,
          Invocation.method(
            #getOrDefault,
            [
              key,
              defaultValue,
            ],
          ),
        ),
      ) as T);

  @override
  bool hasProvider(String? providerKey) => (super.noSuchMethod(
        Invocation.method(
          #hasProvider,
          [providerKey],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasGuard(String? guardName) => (super.noSuchMethod(
        Invocation.method(
          #hasGuard,
          [guardName],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [TokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenService extends _i1.Mock implements _i4.TokenService {
  MockTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>> storeToken(
          Map<String, dynamic>? tokenData) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeToken,
          [tokenData],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>?> findToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #findToken,
          [token],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<Map<String, dynamic>>> findTokensByUser(
    dynamic userId, [
    String? guard,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #findTokensByUser,
          [
            userId,
            guard,
          ],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<int> deleteToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [token],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> deleteUserTokens(
    dynamic userId, {
    String? guard,
    Map<String, dynamic>? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserTokens,
          [userId],
          {
            #guard: guard,
            #filter: filter,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<Map<String, dynamic>>> findTokensBySession(
    String? sessionId, [
    String? guard,
    String? type,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #findTokensBySession,
          [
            sessionId,
            guard,
            type,
          ],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<int> invalidateSession(
    String? sessionId, [
    String? guard,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invalidateSession,
          [
            sessionId,
            guard,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> cleanupExpiredTokens() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredTokens,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<Map<String, dynamic>> blacklistToken(
          Map<String, dynamic>? tokenData) =>
      (super.noSuchMethod(
        Invocation.method(
          #blacklistToken,
          [tokenData],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<bool> isTokenBlacklisted(String? token) => (super.noSuchMethod(
        Invocation.method(
          #isTokenBlacklisted,
          [token],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
